"""Create Board Model

Revision ID: 3ca0db4931ee
Revises: 3c7620131de9
Create Date: 2020-03-19 18:09:28.704799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca0db4931ee'
down_revision = '3c7620131de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master'], ['user.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
