"""add pub_date in article

Revision ID: 459f0f21080d
Revises: 785756bde3c0
Create Date: 2020-03-20 02:47:50.787620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459f0f21080d'
down_revision = '785756bde3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('pub_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'pub_date')
    # ### end Alembic commands ###
