"""delete unique attribute in user model

Revision ID: 664b19fa09b0
Revises: f833287f558d
Create Date: 2020-03-19 20:31:00.299778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664b19fa09b0'
down_revision = 'f833287f558d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_fullname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_fullname_key', 'user', ['fullname'])
    # ### end Alembic commands ###
